"""empty message

Revision ID: 255766e4c9c0
Revises: 5b2f10288712
Create Date: 2016-11-09 16:55:33.724354

"""

# revision identifiers, used by Alembic.
revision = '255766e4c9c0'
down_revision = '5b2f10288712'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imodoka')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imodoka',
    sa.Column('cr_id', sa.INTEGER(), nullable=False),
    sa.Column('cr_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_engine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_drive', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_newprice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cr_body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cr_id', name=u'imodoka_pkey')
    )
    ### end Alembic commands ###
