"""empty message

Revision ID: 3cda77595072
Revises: b423dd3068f5
Create Date: 2016-11-10 09:03:23.847995

"""

# revision identifiers, used by Alembic.
revision = '3cda77595072'
down_revision = 'b423dd3068f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.INTEGER(), nullable=False),
    sa.Column('cr_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_engine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_drive', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cr_newprice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cr_body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cr_id', name=u'cars_pkey')
    )
    ### end Alembic commands ###
