"""empty message

Revision ID: 55dcf787aba6
Revises: None
Create Date: 2016-11-09 12:02:31.645930

"""

# revision identifiers, used by Alembic.
revision = '55dcf787aba6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('cr_brand', sa.String(length=50), nullable=True),
    sa.Column('cr_mark', sa.String(length=50), nullable=True),
    sa.Column('cr_engine', sa.String(length=50), nullable=True),
    sa.Column('cr_drive', sa.String(length=50), nullable=True),
    sa.Column('cr_year', sa.String(length=50), nullable=True),
    sa.Column('cr_newprice', sa.Integer(), nullable=True),
    sa.Column('cr_body', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cr_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    ### end Alembic commands ###
