"""empty message

Revision ID: 5b2f10288712
Revises: cccf14399837
Create Date: 2016-11-09 12:59:38.373967

"""

# revision identifiers, used by Alembic.
revision = '5b2f10288712'
down_revision = 'cccf14399837'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('cr_brand', sa.String(length=50), nullable=True),
    sa.Column('cr_mark', sa.String(length=50), nullable=True),
    sa.Column('cr_engine', sa.String(length=50), nullable=True),
    sa.Column('cr_drive', sa.String(length=50), nullable=True),
    sa.Column('cr_year', sa.String(length=50), nullable=True),
    sa.Column('cr_newprice', sa.Float(), nullable=True),
    sa.Column('cr_body', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cr_id')
    )
    op.create_table('imodoka',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('cr_brand', sa.String(length=50), nullable=True),
    sa.Column('cr_mark', sa.String(length=50), nullable=True),
    sa.Column('cr_engine', sa.String(length=50), nullable=True),
    sa.Column('cr_drive', sa.String(length=50), nullable=True),
    sa.Column('cr_year', sa.String(length=50), nullable=True),
    sa.Column('cr_newprice', sa.Float(), nullable=True),
    sa.Column('cr_body', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cr_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imodoka')
    op.drop_table('cars')
    ### end Alembic commands ###
