"""empty message

Revision ID: a8fe245f0b9b
Revises: 3cda77595072
Create Date: 2016-11-10 09:03:59.946876

"""

# revision identifiers, used by Alembic.
revision = 'a8fe245f0b9b'
down_revision = '3cda77595072'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('cr_brand', sa.String(length=50), nullable=True),
    sa.Column('cr_mark', sa.String(length=50), nullable=True),
    sa.Column('cr_engine', sa.String(length=50), nullable=True),
    sa.Column('cr_drive', sa.String(length=50), nullable=True),
    sa.Column('cr_year', sa.Integer(), nullable=True),
    sa.Column('cr_newprice', sa.Integer(), nullable=True),
    sa.Column('cr_body', sa.String(length=50), nullable=True),
    sa.Column('cr_category', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('cr_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    ### end Alembic commands ###
