"""empty message

Revision ID: cccf14399837
Revises: fcacc7b781cb
Create Date: 2016-11-09 12:56:50.503242

"""

# revision identifiers, used by Alembic.
revision = 'cccf14399837'
down_revision = 'fcacc7b781cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imodoka')
    op.drop_table('cars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.INTEGER(), nullable=False),
    sa.Column('cr_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_engine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_drive', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_newprice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cr_body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cr_id', name=u'cars_pkey')
    )
    op.create_table('imodoka',
    sa.Column('cr_id', sa.INTEGER(), nullable=False),
    sa.Column('cr_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_engine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_drive', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_newprice', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cr_body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cr_id', name=u'imodoka_pkey')
    )
    ### end Alembic commands ###
