"""empty message

Revision ID: dab938ac5a64
Revises: 255766e4c9c0
Create Date: 2016-11-09 16:58:22.777812

"""

# revision identifiers, used by Alembic.
revision = 'dab938ac5a64'
down_revision = '255766e4c9c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('cr_id', sa.INTEGER(), nullable=False),
    sa.Column('cr_brand', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_engine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_drive', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_year', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cr_newprice', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cr_body', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('cr_id', name=u'cars_pkey')
    )
    ### end Alembic commands ###
