"""empty message

Revision ID: fcacc7b781cb
Revises: 55dcf787aba6
Create Date: 2016-11-09 12:40:55.744240

"""

# revision identifiers, used by Alembic.
revision = 'fcacc7b781cb'
down_revision = '55dcf787aba6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imodoka',
    sa.Column('cr_id', sa.Integer(), nullable=False),
    sa.Column('cr_brand', sa.String(length=50), nullable=True),
    sa.Column('cr_mark', sa.String(length=50), nullable=True),
    sa.Column('cr_engine', sa.String(length=50), nullable=True),
    sa.Column('cr_drive', sa.String(length=50), nullable=True),
    sa.Column('cr_year', sa.String(length=50), nullable=True),
    sa.Column('cr_newprice', sa.Integer(), nullable=True),
    sa.Column('cr_body', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cr_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imodoka')
    ### end Alembic commands ###
